version: '3.9'
services:
  scout:
    container_name: scout
    volumes:
    - "/etc/timezone:/etc/timezone:ro"
    - "/etc/localtime:/etc/localtime:ro"
    environment:
      TZ: "America/New_York"
      env: "${env:-development}"
    build:
      context: .
      dockerfile: dockerfile
    restart: always
    networks:
      - scout_network
    ports:
      - '8000:8000'


networks:
  scout_network:
    name: scout_network
