version: '3.9'
services:
  scout:
    network_mode: "host"
    container_name: scout
    volumes:
    - "/etc/timezone:/etc/timezone:ro"
    - "/etc/localtime:/etc/localtime:ro"
    - type: bind
      source: /media/plex/downloads
      target: /media/plex/downloads
    - type: bind
      source: /media/plex/movies
      target: /media/plex/movies
    environment:
      TZ: "America/New_York"
      env: "${env:-development}"
    build:
      context: .
      dockerfile: dockerfile
    restart: always
    ports:
      - '8000:8000'
