name: "Scout API"
port: ":9000"
version: "v.0.5"
datadir: "/media/plex/downloads/"
sentry:
   dsn: "https://30bed76e31629f3b7b878e03152102b9@o559921.ingest.sentry.io/4506050250276864"

quality: "1080p"

sources:
   - "TGxGoodies"
   - "BedBug"
   - "QxR"
   - "YIFY"

negativeWords:
   - "webrip"
   - "rip"
   - "hdts"
